# Generated by Django 3.1rc1 on 2020-08-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='marks',
        ),
    ]
