# Generated by Django 3.1rc1 on 2020-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0002_auto_20200811_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.CharField(max_length=100),
        ),
    ]
