# Generated by Django 3.1rc1 on 2020-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0003_auto_20200811_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Food_Code', models.CharField(blank=True, default='NULL', max_length=25, unique=True)),
                ('Food_Name', models.CharField(blank=True, default='NULL', max_length=50)),
                ('Veg', models.BooleanField(default=False)),
                ('Nveg', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default='NULL', max_length=50)),
                ('item_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('special_item', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='NULL', max_length=250)),
                ('Meal_Time', models.CharField(blank=True, default='NULL', max_length=40)),
                ('Rating', models.CharField(blank=True, default='NULL', max_length=30)),
                ('Preparation_Time', models.IntegerField(blank=True, default='NULL')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
