# Generated by Django 3.1rc1 on 2020-08-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0004_auto_20200812_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Nveg',
            new_name='VegNveg',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Veg',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Preparation_Time',
            field=models.IntegerField(blank=True, max_length=30),
        ),
    ]
