# Generated by Django 3.1rc1 on 2020-08-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0006_auto_20200813_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='Menu_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='Food_Code',
            field=models.CharField(blank=True, default='NULL', max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
