# Generated by Django 3.1rc1 on 2020-08-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0007_auto_20200813_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['Food_Code']},
        ),
    ]
