# Generated by Django 3.1rc1 on 2020-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0009_auto_20200813_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Food_Code',
            field=models.CharField(blank=True, default='NULL', max_length=25, primary_key=True, serialize=False),
        ),
    ]
