# Generated by Django 3.1rc1 on 2020-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0010_auto_20200813_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Food_Code',
            field=models.IntegerField(blank=True, default='NULL', primary_key=True, serialize=False),
        ),
    ]
