# Generated by Django 3.1rc1 on 2020-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapi', '0011_auto_20200813_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Food_Code',
            field=models.IntegerField(default='NULL', primary_key=True, serialize=False),
        ),
    ]
